import { Demo } from "@/components/demo";
import { useIsMounted } from "@/hooks/useIsMounted";
import styles from "@/styles/Home.module.css";
import { usePrivy } from "@privy-io/react-auth";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const isMounted = useIsMounted();
  const { authenticated, login, logout, connectOrCreateWallet } = usePrivy();

  const handleLogin = async () => {
    try {
      if (authenticated) {
        await logout();
      }
      login();
      connectOrCreateWallet();
    } catch (e) {
      console.log((e as any).message as any);
    }
  };

  if (!isMounted) return null;

  return (
    <>
      <Head>
        <title>Create Greenfield App</title>
        <meta name="description" content="Generated by create Greenfield app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {!authenticated ? (
          <>
            <button
              style={{
                minWidth: "250px",
                height: "50px",
                paddingLeft: "5px",
                paddingRight: "5px",
              }}
              onClick={handleLogin}
            >
              Login Please
            </button>
          </>
        ) : (
          <Demo />
        )}
      </main>
    </>
  );
}
